name: anomaly-detection
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - numpy
  - matplotlib
  - scikit-learn
  - pandas
  - jupyter
  - pip
